//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxonomy.Schedule.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
        public int Request_Id { get; set; }
        public int Sender_Id { get; set; }
        public int Owner_Id { get; set; }
        public Nullable<bool> IsReaded { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Request Request { get; set; }
    }
}
