//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxonomy.Schedule.Wpf.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class taxonamyEntities : DbContext
    {
        public taxonamyEntities()
            : base("name=taxonamyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brigade> Brigade { get; set; }
        public virtual DbSet<BrigadeShedule> BrigadeShedule { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Shedule> Shedule { get; set; }
        public virtual DbSet<TypeChange> TypeChange { get; set; }
    }
}
